### ISSUE TITLE
FileNotFoundError: [Errno 2] schema

### ISSUE THREAD

**Issue by mbacicc** [debba/greenpass-covid19-qrcode-decoder#8]
Appena clonato il repo, genera questo errore:

```
127.0.0.1 - - [12/Jan/2022 21:09:25] "POST /qrdata HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "C:\git\greenpass-covid19-qrcode-decoder\venv\Lib\site-packages\werkzeug\serving.py", line 319, in run_wsgi
    execute(self.server.app)
  File "C:\git\greenpass-covid19-qrcode-decoder\venv\Lib\site-packages\werkzeug\serving.py", line 308, in execute
    application_iter = app(environ, start_response)
  File "C:\git\greenpass-covid19-qrcode-decoder\venv\Lib\site-packages\flask\app.py", line 2088, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\git\greenpass-covid19-qrcode-decoder\venv\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.handle_exception(e)
  File "C:\git\greenpass-covid19-qrcode-decoder\lib\datamapper.py", line 71, in __init__
    self.__set_schema(schema_url)
  File "C:\git\greenpass-covid19-qrcode-decoder\lib\datamapper.py", line 53, in __set_schema
    self.schema = get_json_file(schema_url, "https://raw.githubusercontent.com/ehn-dcc-development/ehn-dcc-schema/release/1.3.0/DCC.combined-schema.json")
  File "C:\git\greenpass-covid19-qrcode-decoder\lib\utils.py", line 33, in get_json_file
    local_file = download_from_remote(remote_url, local_file)
  File "C:\git\greenpass-covid19-qrcode-decoder\lib\utils.py", line 22, in download_from_remote
    with open(local_file, "wb") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\git\\greenpass-covid19-qrcode-decoder\\data\\DCC.combined-schema.json'
```

Si risolve se si crea manualmente la cartella data.

Puoi aggiungere un check se la cartella esiste prima di "C:\git\greenpass-covid19-qrcode-decoder\lib\utils.py", line 22, in download_from_remote. Nel caso in cui non esista la crei.

**Comment by debba** [comment]
Grazie, ottimo suggerimento.
Ho fatto due miglioramenti:

- aggiunto .gitkeep nella cartella data ed esclusi nel file .gitignore i file .json all'interno
- nel caso la cartella data non esista, viene automaticamente creata.

Se vuoi contribuire al progetto o alla documentazione, sentiti libero di farlo.
